set_property SRC_FILE_INFO {cfile:d:/220110630/proj_single_cycle/proj_single_cycle.srcs/sources_1/ip/cpuclk/cpuclk.xdc rfile:../proj_single_cycle.srcs/sources_1/ip/cpuclk/cpuclk.xdc id:1 order:EARLY scoped_inst:Clkgen/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/220110630/proj_single_cycle/proj_single_cycle.srcs/constrs_1/new/miniRV_SoC.xdc rfile:../proj_single_cycle.srcs/constrs_1/new/miniRV_SoC.xdc id:2} [current_design]
current_instance Clkgen/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
current_instance
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list cpu_clk_BUFG]]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {dig_en_OBUF[0]} {dig_en_OBUF[1]} {dig_en_OBUF[2]} {dig_en_OBUF[3]} {dig_en_OBUF[4]} {dig_en_OBUF[5]} {dig_en_OBUF[6]} {dig_en_OBUF[7]}]]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 25 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {U_DLED_Interface/count[0]} {U_DLED_Interface/count[1]} {U_DLED_Interface/count[2]} {U_DLED_Interface/count[3]} {U_DLED_Interface/count[4]} {U_DLED_Interface/count[5]} {U_DLED_Interface/count[6]} {U_DLED_Interface/count[7]} {U_DLED_Interface/count[8]} {U_DLED_Interface/count[9]} {U_DLED_Interface/count[10]} {U_DLED_Interface/count[11]} {U_DLED_Interface/count[12]} {U_DLED_Interface/count[13]} {U_DLED_Interface/count[14]} {U_DLED_Interface/count[15]} {U_DLED_Interface/count[16]} {U_DLED_Interface/count[17]} {U_DLED_Interface/count[18]} {U_DLED_Interface/count[19]} {U_DLED_Interface/count[20]} {U_DLED_Interface/count[21]} {U_DLED_Interface/count[22]} {U_DLED_Interface/count[23]} {U_DLED_Interface/count[24]}]]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {U_DLED_Interface/wd_r[0]} {U_DLED_Interface/wd_r[1]} {U_DLED_Interface/wd_r[2]} {U_DLED_Interface/wd_r[3]} {U_DLED_Interface/wd_r[4]} {U_DLED_Interface/wd_r[5]} {U_DLED_Interface/wd_r[6]} {U_DLED_Interface/wd_r[7]} {U_DLED_Interface/wd_r[8]} {U_DLED_Interface/wd_r[9]} {U_DLED_Interface/wd_r[10]} {U_DLED_Interface/wd_r[11]} {U_DLED_Interface/wd_r[12]} {U_DLED_Interface/wd_r[13]} {U_DLED_Interface/wd_r[14]} {U_DLED_Interface/wd_r[15]} {U_DLED_Interface/wd_r[16]} {U_DLED_Interface/wd_r[17]} {U_DLED_Interface/wd_r[18]} {U_DLED_Interface/wd_r[19]} {U_DLED_Interface/wd_r[20]} {U_DLED_Interface/wd_r[21]} {U_DLED_Interface/wd_r[22]} {U_DLED_Interface/wd_r[23]} {U_DLED_Interface/wd_r[24]} {U_DLED_Interface/wd_r[25]} {U_DLED_Interface/wd_r[26]} {U_DLED_Interface/wd_r[27]} {U_DLED_Interface/wd_r[28]} {U_DLED_Interface/wd_r[29]} {U_DLED_Interface/wd_r[30]} {U_DLED_Interface/wd_r[31]}]]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list U_DLED_Interface/count_end]]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list U_DLED_Interface/counting]]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list Bridge/rst_to_dig]]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets cpu_clk_BUFG]
